# Generated by Django 4.0.4 on 2022-04-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
