# Generated by Django 4.0.4 on 2022-04-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
