# Generated by Django 4.0.4 on 2022-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
