# Generated by Django 4.0.4 on 2022-04-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
